# Customer Churn Modelling with Tensorflow 2.0 and Keras:
#### Thirumurugan Ramar

In [4]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd

In [3]:
tf.__version__

'2.0.0'

In [5]:
# Import the dataset
data = pd.read_csv('Customer_Churn_Modelling.csv')

In [6]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
x= data.drop(labels=['CustomerId','RowNumber','Surname','Exited'],axis = 1)
y= data['Exited']

In [8]:
x.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [9]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [10]:
# data preprocessing
from sklearn.preprocessing import LabelEncoder

In [13]:
label1 = LabelEncoder()
x['Geography'] = label1.fit_transform(x['Geography'])
label2 = LabelEncoder()
x['Gender'] = label2.fit_transform(x['Gender'])

In [17]:
x = pd.get_dummies(x, drop_first=True, columns=['Geography'])
x.head(10)

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   
5          645       1   44       8  113755.78              2          1   
6          822       1   50       7       0.00              2          1   
7          376       0   29       4  115046.74              4          1   
8          501       1   44       4  142051.07              2          0   
9          684       1   27       2  134603.88              1          1   

   IsActiveMember  EstimatedSalary  Geography_1  Geography_2  
0               1        101348.88            0            0  
1               1        112542.58            0            1  
2               0        113931.57            0            0  
3               0         93826.63            0            0  
4               1         79084.10            0            1  
5               0        149756.71            0            1  
6               1         10062.80            0            0  
7               0        119346.88            1            0  
8               1         74940.50            0            0  
9               1         71725.73            0            0

In [19]:
#train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0, stratify = y)

In [20]:
#feauture scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [21]:
X_train,X_test

(array([[-1.24021723, -1.09665089,  0.77986083, ...,  1.64099027,
         -0.57812007, -0.57504086],
        [ 0.75974873,  0.91186722, -0.27382717, ..., -1.55587522,
          1.72974448, -0.57504086],
        [-1.72725557, -1.09665089, -0.9443559 , ...,  1.1038111 ,
         -0.57812007, -0.57504086],
        ...,
        [-0.51484098,  0.91186722,  0.87565065, ..., -1.01507508,
          1.72974448, -0.57504086],
        [ 0.73902369, -1.09665089, -0.36961699, ..., -1.47887193,
         -0.57812007, -0.57504086],
        [ 0.95663657,  0.91186722, -1.32751517, ...,  0.50945854,
         -0.57812007,  1.73900686]]),
 array([[-1.975956  , -1.09665089,  0.1093321 , ..., -0.15254674,
          1.72974448, -0.57504086],
        [ 0.64576103, -1.09665089, -1.42330499, ...,  0.36818473,
          1.72974448, -0.57504086],
        [ 0.12763513,  0.91186722,  2.40828774, ..., -1.46485588,
         -0.57812007,  1.73900686],
        ...,
        [-1.20912968,  0.91186722,  0.20512192, ..., -

#### Building Artificial neural network:

In [25]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense

In [27]:
model = Sequential()
model.add(Dense(x.shape[1], activation='relu', input_dim = x.shape[1]))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [28]:
x.shape

(10000, 11)

In [29]:
#compiling
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [30]:
model.fit(X_train, y_train.to_numpy(), batch_size = 10, epochs = 25, verbose = 1)

Train on 8000 samples
Epoch 1/25
8000/8000 [==============================] - 4s 552us/sample - loss: 0.4455 - accuracy: 0.8090
Epoch 2/25
8000/8000 [==============================] - 2s 199us/sample - loss: 0.4018 - accuracy: 0.8307
Epoch 3/25
8000/8000 [==============================] - 2s 200us/sample - loss: 0.3695 - accuracy: 0.8474
Epoch 4/25
8000/8000 [==============================] - 2s 218us/sample - loss: 0.3526 - accuracy: 0.8543
Epoch 5/25
8000/8000 [==============================] - 2s 195us/sample - loss: 0.3435 - accuracy: 0.8580
Epoch 6/25
8000/8000 [==============================] - 1s 183us/sample - loss: 0.3397 - accuracy: 0.8579
Epoch 7/25
8000/8000 [==============================] - 2s 214us/sample - loss: 0.3358 - accuracy: 0.8611
Epoch 8/25
8000/8000 [==============================] - 2s 188us/sample - loss: 0.3338 - accuracy: 0.8615
Epoch 9/25
8000/8000 [==============================] - 1s 183us/sample - loss: 0.3316 - accuracy: 0.8618
Epoch 10/25
8000/8000 [=

In [31]:
y_pred = model.predict_classes(X_test)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]])

In [32]:
y_test

1344    1
8167    0
4747    0
5004    1
3124    1
       ..
9107    0
8249    0
8337    0
6279    1
412     0
Name: Exited, Length: 2000, dtype: int64

In [33]:
model.evaluate(X_test, y_test.to_numpy())

2000/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.3583057818412781, 0.8555]

In [34]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8555